name: pap_firebase_remote_config
description: Flutter plugin for Firebase Remote Config in Mobile and Web platforms.
version: 0.0.1
author: yaama
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: 0.9.0-dev.0
  googleapis_auth: ^1.1.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
